// <auto-generated />
using HNGProjectTaskOneAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HNGProjectTaskOneAPI.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20221029183341_InitialiseDB")]
    partial class InitialiseDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HNGProjectTaskOneAPI.Model.HNGStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<bool>("backend")
                        .HasColumnType("bit");

                    b.Property<string>("bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("slackUsername")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HNGStudents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            age = 30,
                            backend = true,
                            bio = "I am a backend developer",
                            slackUsername = "Olisaemeka"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
